### ISSUE TITLE
Screenshot broken

### ISSUE THREAD

**Issue by astrographer** [davidson16807/tectonics.js#10]
Looking over the latest version, I found the Screenshot button(and <P> shortcut) was no longer available. For my purposes, at least, this is a vital element of functionality.

MacOS 10.12.6
Firefox 56.0.2

**Comment by davidson16807** [comment]
OK, reproduced. That's really weird but I suspect some problem with the recent move to Vue.js. Will look into it tonight.

**Comment by davidson16807** [comment]
The screenshot button is actually two html tags: a button and an anchor within the button. When the user clicks the screenshot button, the event reaches the button first. The button uses Vue.js to configure the anchor so that it downloads the data. The event then propagates to the anchor, which does the actual downloading. It's done this way because only an anchor can download the file, but an event has to occur beforehand to configure the anchor. 

That's how it works in theory. In practice, Vue.js doesn't update the data before the anchor downloads, at least not in Firefox. I tried forcing Vue to update the anchor using $forceUpdate(), but it still doesn't work. I'm not going to investigate this further. I'm falling back on jQuery to do the data update, as was done previously. I was trying to phase out jQuery, but it's apparent from this and other problems that Vue.js is not a complete replacement. 

I still have to commit these fixes and push them to prod. More to come.

**Comment by astrographer** [comment]
I don't know what the advantages are to Vue.js, but would this help?

https://forum.vuejs.org/t/component-not-updating-when-data-changes/3163/3

**Comment by davidson16807** [comment]
The fix is out. Go check it.

The screenshot bug is unrelated to the pause bug. I'd file a separate issue for that. 

The pause bug has more to do with how the ScalarHeatDisplay class is defined within the "View" layer (the "View" layer is completely different from "Vue". Yeah, I know that's confusing, but that's really the only way I can name them. I describe them on the [wiki]
(https://github.com/davidson16807/tectonics.js/wiki/Developer%27s-Overview))

Vue.js is a "Model-View-Control" framework for javascript. It's like React.js or Angular.js, if that means anything. React and Angular are more popular, but they're way to opinionated and I'm sick of working with them. 

Vue.js is much more lightweight, and it plays nice with jQuery so it's easy for tectonics.js to migrate towards. I like it. I'll have to write a blog post about it some time. It still has problems, like we see here, but the community isn't so militant to assert you can't use jQuery workarounds.

I didn't realize anyone found the "p" shortcut handy so I didn't bother to reimplement it during the switch to Vue. I'll have to add it back.

**Comment by davidson16807** [comment]
keyboard shortcuts have been reimplemented

**Comment by davidson16807** [comment]
Alright, I don't expect it should be a problem again. Feel free to open a new issue if otherwise.
