### ISSUE TITLE
Log or console record of univariate stats

### ISSUE THREAD

**Issue by astrographer** [davidson16807/tectonics.js#14]
I've been having trouble reconnecting the temperature model to altitude. I'm thinking this might be due to some problems with the values coming out of the altitude model itself. To test this, if it's not possible to export higher-order rasters(16-bit integer with at least min and max recorded, or optimally 32-bit floats…😌), it would be a real boon to have access to minimum, maximum, mean, median, possibly mode, and standard deviation to somewhere accessible(console output, a log record, an exported text file, or just as temporary text labels on the screen). This could perhaps be toggled at startup with a "univar" flag in the url…

I'm thinking of this mainly for altitude, but I'm sure it would be useful for precipitation, temperature, biomass or any other quantitative values(again, toggled perhaps by "alt.univar," "prec.univar," etc.

My preference would simply be an onscreen button menu to export a text file with the univariate stats for the selected parameter, but I'm flexible and overjoyed if you just decide to add this. 

Thank you,
Colin

**Comment by davidson16807** [comment]
If you know the name of the raster, you can do this in the console right now: 

```
 Float32Dataset.average(world.displacement) - world.SEALEVEL
```

 * "world.displacement" stores altitude in meters relative to some arbitrary datum level

 * "Float32Dataset.average" finds the average across a raster

 * "world.SEALEVEL" is the sealevel relative to some arbitrary datum level, so taking displacement minus sea level will give you elevation in meters above sealevel. 

Most browser consoles have some sort of autocomplete, so you can see a full list of functions provided by "Float32Dataset", not to mention a full list of rasters provided by "world".

For a while now I've wanted to implement better ways to view data in a nonspatial way: histograms, time series charts, min/max/average statistics, etc. Never got to it because there was no demand and I had other ways to do it, so I'll prioritize this.

**Comment by davidson16807** [comment]
I've implemented a chart display with statistics on an experimental branch. I didn't implement mode because it wound up not making a lot of sense for floating point numbers. I'm hoping to move this to prod later this evening. 

![screen shot 2017-12-13 at 9 33 21 am](https://user-images.githubusercontent.com/5824741/33946908-a63d5452-dfe8-11e7-89ed-a04782412e62.png)

You mention having an "export" functionality. What sort of export do you have in mind? I'm picturing a csv with columns for lat, long, the currently displayed field, and any other major attributes that are relevant to the user:  elevation, temperature, precip, npp. There are other things we could include and it wouldn't be hard to add it, but I'm not sure how useful they'd be to the user: plate, crust age, density, thickness, sima/sial fraction, etc.

**Comment by astrographer** [comment]
Generally looking pretty darn good. I'm assuming horizontal axis is value and vertical axis is count.
As to export… your csv sounds good. What I would love to see would be a full float(32-bit) export to Virtual Terrains .bt, .hf2/hfz, or geotiff. That might not be well-received by the wider audience, but for gis dweebs like me, it would be a godsend! PlateID would definitely be useful.

Game files might be of pretty limited value, except for things like KSP or flight simulator-type apps. The scale is just too small, I think.

Now that I'm seeing the raw elevation values, I understand why the altitude-based aspect of temperature generation is failing so badly. But that's a whole other issue…

**Comment by astrographer** [comment]
It also might be nice to have the option to limit stats and charting to land areas. Perhaps when the ocean is displayed, stats and charts are created based on land area; when the ocean is hidden, stats and charts cover the full surface.

**Comment by davidson16807** [comment]
I'm going to refocus priority on this issue now that #18 is in test. I figure this one is so close to done anyways.

Remaining work to close out the story:

 * implement a csv export
 * filter stats based on whether "Ocean" is toggled

A separate issue will be created for geospatial export formats. I have no preference for which gets implemented, though the documention for geotiff looks annoying. I'll let you decide which to prioritize.

**Comment by davidson16807** [comment]
I've implemented a rudimentary csv export and filter based on ocean visibility. Columns for precip, temp, npp etc should be added to the csv after work on #9. Issue #9 will be my next focus.
