### ISSUE TITLE
CSV exports are missing content in Firefox

### ISSUE THREAD

**Issue by davidson16807** [davidson16807/tectonics.js#40]
images:

http://www.fileconvoy.com/dfl.php?id=g28ebb083b4d12461100015484473d648198f2a42bc

A fix is out in prod, now. Give it a shot and let me know if it works, @BurnerCorvus

**Comment by BurnerCorvus** [comment]
Almost works now. The .csv export has all the data, but for lat/long which are all zeroes. At least I have the number of cells, 10,242 which divided into 510.1^6 km surface area gets 498 square km per cell, 22.3 km per side.

And Edge is working, not that I use it a lot.

**Comment by johnpmayer** [comment]
Seeing the same behavior, only zeroes for lat/long, in Chrome 72

**Comment by johnpmayer** [comment]
Proximate cause: In CsvExporter, Float32Raster(world.grid) is returning a buffer of all zeroes

**Comment by davidson16807** [comment]
You seem to be on to something, @johnpmayer. Checks out on my machine. I've released the fix to prod. @BurnerCorvus, could you verify?

**Comment by BurnerCorvus** [comment]
It does! (happy dance).  Since both axes have positive and negative numbers, I am assuming 0,0 is the point where the equator and an arbitrary prime meridian meet with positive latitudes being north and negative being south while the longitudes run positive one way and negative the other until they meet at 180.

Oh, and in my earlier post, the 22.3km per side was for a square -- I'd forgotten the cells are triangles.  Recalculating for an equilateral triangle gets 33.9km per side, pretty tiny for a worldwide map.  Are there a bunch of cells lumped together for the map's triangles?

**Comment by davidson16807** [comment]
>0,0 is the point where the equator and an arbitrary prime meridian meet with positive latitudes being north and negative being south while the longitudes run positive one way and negative the other until they meet at 180

Yep, all of that's correct.

> Recalculating for an equilateral triangle gets 33.9km per side, pretty tiny for a worldwide map

Hrm, we're talking about the average distance between vertices, right?. You can actually get a much better estimate by querying the developer console:

```
> world = sim.focus
> world.grid.average_distance * world.radius
239352.8796042956
```

239km. You might have missed a decimal place.

>Are there a bunch of cells lumped together for the map's triangles?

No, the model requires equidistant vertices, it's a very core assumption.

**Comment by davidson16807** [comment]
By the way, since we've got this working again, I'm going to close out the issue. Let's keep the conversation going though on issue #36.

**Comment by BurnerCorvus** [comment]
Ah.  So the model is a series of points and the forms show on the map as triangles because they're just the shortest distance to the surrounding points?  239km per side makes me feel a lot more comfortable.

I'll check my work but it's pretty pedantic anyway.  Living in the Basin and Range part of Arizona I'm well aware of the problems trying to map out squares (or triangles for that matter) on a spherical surface.  The "main milers" as we call them follow the lines of the Range and Township survey and have to be jiggered more often than you think to make them fit.  https://tinyurl.com/y2e3o9bz

It's all part of that globe conspiracy the flat earthers keep going on about.

**Comment by davidson16807** [comment]
>So the model is a series of points and the forms show on the map as triangles because they're just the shortest distance to the surrounding points? 

Correct, but the positions for the vertices are statically defined: there's always the same number of them in a grid, they don't move around independently from one another, and they always keep the same number of neighbors. It's just easier this way to render the world using vertex shaders. 

>It's all part of that globe conspiracy the flat earthers keep going on about.

🤣

So Phoenix or Tuscon? I was thinking about moving there not too long ago; wasn't sure about the heat. Very geologically inspiring. What do you do there?

**Comment by BurnerCorvus** [comment]
Phoenix area. Mesa, actually, two doors to the right of Phoenix proper.

It is an interesting state to be in geologically speaking because, as I've put it, the bones show. There is a book, Roadside Geology of Arizona https://smile.amazon.com/Roadside-Geology-Arizona-Halka-Chronic/dp/0878421475/ref=sr_1_1?crid=34NORDQIAGNES&keywords=roadside+geology+of+arizona&qid=1552835698&s=gateway&sprefix=roadside+geology%2Caps%2C194&sr=8-1 , that talks briefly about what you're looking at along all of the major routes in the state, Interstates and US highways, plus a few "special places" like the Grand Canyon.

You get used to the summer heat -- or throw up you hands and move away.  Tucson is a bit higher than Phoenix and so is a few degrees cooler, not that there's much difference between 115 and 112.  Mainly you avoid wandering around outside in the daytime, spending your time indoors or an AC-equipped vehicle until after sunset.

If you mean what so I do insofar as work is concerned, I'm retired.  This means I'm busier than ever and had to learn to use Google Calendar to keep track of it all.  Most of the entries deal with my being a participant and volunteer for Burning Man https://burningman.org/ .

**Comment by davidson16807** [comment]
Ha! I was in Mesa just this January (trying to escape the cold, I'm from Iowa) 😀

Might have to check out that book you mention. Some of those "special places" are what gave me the most inspiration for tectonics.js. I can remember thinking about erosion models when visiting the grand canyon, modeling asteroid impacts at Barrington crater...

**Comment by BurnerCorvus** [comment]
January's the time to visit -- it's why we live here. The lowest we got here at the house this year was 36-F and it hasn't been below freezing for at least three years. A couple years ago when we were ramping up the temperature in June (actually our hottest month) the afternoon drive guys were giving tips on how to survive to the newcomers. They said, "Our summer is like your winter: It's when the weather can kill you."

And it's Barringer Crater :-)

**Comment by davidson16807** [comment]
>Our summer is like your winter: It's when the weather can kill you.

True, hard to pick between 130°F in the shade or -40 windchill. Personally I'd miss seeing the snow fall, but I guess that's what Flagstaff's for. 😀

> Barringer Crater

well, at least I got the first half right 😅
