### ISSUE TITLE
Loading past sims?

### ISSUE THREAD

**Issue by samdkatz** [davidson16807/tectonics.js#44]
Hey Carl, I used this tool a while back to generate a world map I'm really happy with for my conworld. I saved the sim so I could make a map of the world's prehistoric "pangea", but now it won't load. I see there was an issue that was updated on March 11, but I think that only fixes it for sims saved after the update. Is there anything I can do with this old file?

**Comment by davidson16807** [comment]
When did you save the file? Would you be able to upload it? If so, I'll take a look at it to see what we can do. 

Are you comfortable using a repository view, like gitkraken? If so you can load up an older version the project on your machine and open the save file there. However, this won't let you use any of the features that were recently introduced (atmospheric scattering, for instance)

**Comment by samdkatz** [comment]
Looks like I saved it... a while ago. 2018-05-01. Attaching three saves (same world at different times; in case something actually happened to the files on my machine, you have a few options). Since Tectonics.js can run time backwards, if you're doing something to the file to help me out, any one of these is fine -- no need to do all three!

As for using a repository view, I've never done that before but I'm perfectly happy to try it.

[leniste.zip](https://github.com/davidson16807/tectonics.js/files/3137683/leniste.zip)

**Comment by davidson16807** [comment]
I took a look at the zip file and I've come to believe it's a nontrivial amount of work to write a conversion script. A lot of stuff happened to the save file format since May in order to support orbital mechanics and I'm pressed for time as it is. I think we should consider backwards compatibility if we update the save file format again, but for right now our time is best spent on looking forwards.  

That said, I think there's a quick way to get this working: download [this file](https://github.com/davidson16807/tectonics.js/archive/fd5878ce2e8db7214381d320e6c95f55be5d8e16.zip), unzip the contents, open index.html in your browser of choice, and drag and drop your save file into the application. You should see this: 

![leniste-18 4My (1)](https://user-images.githubusercontent.com/5824741/57735615-d265ab00-766a-11e9-8ccb-65b7f31dd8d7.png)

Another thing to do would be to load up the seed in the most recent version of the application. Since the world generation algorithm hasn't changed you should get the same world. It looks like the model back then used the world name as it's seed, so try:

http://davidson16807.github.io/tectonics.js/?seed=leniste

When I go there, I see this:

![togois-0 0245y](https://user-images.githubusercontent.com/5824741/57736589-27ef8700-766e-11e9-9800-09db7f3b44ad.png)

The name of the world is different ("togois" instead of "leniste") but it should have the same appearance. There may be some other differences as well, particularly with how the plates move. On the bright side, this means you get all the new features of the model (new save file format, orbital mechanics, seasonal temperature, atmospheric scattering, etc.)

Let me know how that works for you. Would you be fine with me closing out the story?

**Comment by samdkatz** [comment]
Hi Carl,

Sorry, but I'm still not quite getting it. If I try to run it on the new
version any faster than 100y/s, it does this:
[image: Screen Shot 2019-05-15 at 5.29.04 PM.png]

And the old one does something similar when I try to load a sim:
[image: Screen Shot 2019-05-15 at 5.32.41 PM.png]

It's really not that important, though. You can close the story, and just
let me know if the speed issue in the new one has an easy fix. I love the
moving ice caps in the new version, by the way!

Sam

**Comment by davidson16807** [comment]
>It's really not that important, though. You can close the story, and just
let me know if the speed issue in the new one has an easy fix. I love the
moving ice caps in the new version, by the way!

Thanks! I'm not sure about the speed issue though. You mention something happens past 100y/s but I can't see the image. Could you try reuploading, or maybe try a file site like imgur? What browser are you using?

**Comment by davidson16807** [comment]
I'll close out this issue since it sounds like the other problem you mention may be off topic. Feel free to open up a new issue for the other problem if you feel it's needed.
